CREATE SCHEMA `smservices`
  DEFAULT CHARACTER SET utf8;

CREATE USER 'sms'@'%' IDENTIFIED BY 'smsdev';

GRANT ALL PRIVILEGES ON smservices.* TO 'sms'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE, ALTER, REFERENCES, CREATE, DROP, INDEX, LOCK TABLES, CREATE ROUTINE, TRIGGER, CREATE TEMPORARY TABLES, ALTER ROUTINE, SHOW VIEW ON smservices.* TO sms;

FLUSH PRIVILEGES;

